language: scala
scala:
  - 2.11.12
matrix:
  include:
    - scala: 2.12.10
      jdk: openjdk11
before_install:
  - git fetch --tags

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - env: TEST="build"
      script: sbt +compile +test scalafmtCheckAll scalastyle
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: Nn7l55GE56n+wrOGmpFxrZb6KMhT/rQd/LGDZzqfkphGLaAOFFycfLVOSJ3cftFpBPYi2nOLDJbWXAe5MNJopJlr75iujqi+MLrqdGH8uynXsREJJVxOTm2dQAw094aOLfylxN0jWLrxckQ1Ps5ESRuHAMnm/36/zhS78z+xC4jzi06vbI7+kWo/DnRvHCq5Nz5F/f1cHJfqebQbaFNiLCg9f+rlmREfJG/54dT+tdMO8NAbTJR4GHl5IX0UNUkhz30Obtxax+Lt1zQe0TigCbO4KdoownuO5aHAkoLtbOpiTlwXkMARJJC9/TBORWM5dLISvXwlKwd1KOS2JI5NJWATsbBnzEqS/DfV0sp6wWucO3TpgPVqdIpgOOnKEszpr45Facyg3/Zjjs0K/Bo35BTdWrhKBTOBrbrcuCs88i9sy/H4G565enfVS9JbWhFxMi5dZFii3QQyBUwKCjQn0ytC699pxLQ8fs1NsqhBIZDgsiXIV6e6fdpUUY9nvmgjhttPi6JImBbbht/6BSn2UQm8Z3uvEpjYdurKwkK4b404jXzDhcqCyZH21vGGaTV3TKYdR/F9rSnCFXlOCEoFmO7qOsePcSIhZ5VHOi2M+Rmxr/5V88eCtte0Ck/JpkcwpAv86S7DPQFOADdJaFfIBO9ZuhoQEEkMGiecv/ALBYI=
