addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.3.4")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin"   % "1.0.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.6.1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.32")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"           % "1.5.2")
