addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.4")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin"    % "1.0.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.9.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.1.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.7.1")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"           % "1.5.10")
