name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Restore caches
        uses: coursier/cache-action@v8
      - name: Setup Scala
        uses: coursier/setup-action@v3
        with:
          jvm: 21
          apps: sbt
      - name: Run tests
        run: sbt +compile +test scalafmtCheckAll 'scalafixAll --check'
